language: python
sudo: false
dist: xenial

matrix:
    include:
        - python: "2.7"
          env: TOXENV=lint-py27
        - python: "3.6"
          env: TOXENV=lint-py36
        - python: "2.7"
          env: TOXENV=py27
        - python: "3.5"
          env: TOXENV=py35
        - python: "3.6"
          env: TOXENV=py36
        - python: "3.7"
          env: TOXENV=py37

install:
    - travis_retry pip install -U tox coveralls coverage

script:
    - tox

after_success:
    - coverage combine
    - coveralls

notifications:
    email: false
cache:
    pip: true
