language: python
sudo: false

matrix:
    include:
        - python: "2.7"
          env: TOXENV=lint-py27
        - python: "3.6"
          env: TOXENV=lint-py36
        - python: "2.7"
          env: TOXENV=py27
        - python: "3.5"
          env: TOXENV=py35
        - python: "3.6"
          env: TOXENV=py36
        - python: "3.7-dev"
          env: TOXENV=py37
    allow_failures:
        - python: "3.7-dev"
          env: TOXENV=py37

install:
    - travis_retry pip install -r https://raw.githubusercontent.com/plone/buildout.coredev/5.2/requirements.txt
    - travis_retry pip install -U tox coveralls coverage

script:
    - tox

after_success:
    - coverage combine
    - coveralls

notifications:
    email: false
cache:
    pip: true
